/*
 * MQTT-Proxy Crypto Example JavaScript Extension
 *
 * This script demonstrates how to use the cryptographic functions provided by the proxy.
 * To use it, run the proxy with the --script flag:
 * go run ./cmd/mqtt_mitm_proxy --script ./cmd/mqtt_mitm_proxy/crypto_example.js
 *
 * Then, publish a message to the topic 'test/crypto' to trigger the tests.
 * mosquitto_pub -h localhost -p 8883 -t "test/crypto" -m "run"
 */

// -----BEGIN GENERATED FIXTURES-----
// Generated by `go run ./test/crypto_test/main.go`

const ecdsaPrivateKeyPEM = `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEINaMfCLJYgk9TBTlVnaBSjonwLL5koRy9CpdmA1smExRoAoGCCqGSM49
AwEHoUQDQgAEvG/+9Uxu+9lXfRhkKo/U32vYC0LBQbmkQMAWsC6q4MyEDI6H9fxp
aGHSx6/IP5XL0k0sABycijX5xnJTqdlMqg==
-----END EC PRIVATE KEY-----
`;

const ecdsaPublicKeyPEM = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvG/+9Uxu+9lXfRhkKo/U32vYC0LB
QbmkQMAWsC6q4MyEDI6H9fxpaGHSx6/IP5XL0k0sABycijX5xnJTqdlMqg==
-----END PUBLIC KEY-----
`;

const rsaPrivateKeyPEM = `-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA26k4gGVllm8w4S4TSGZ2+naF/pQnzyofyI3tmj5YdkhkYKxV
g958dxnDd0KMnFL/tcGmdiEm+RfE9b7TGxhnANHRnrKp3+TqgaD8BcE+sdIqa4zp
mEybbu27hF3stg7UpgqfYIiKjEYirU9IhTSWFlHrcwz9zV4hMxMpNEM+Phkupm//
6tbnRFphkNntucJ+c3li/pCHlnTMlGO8qiujYK/Y5AcOvYLw96/mi/XN+CnKp1Xv
d76fuReWndFA35OWICicpurpaKS1f+fe3a102Q9dMYiakrkZlRQgRn2VW1WNqluO
AzRK8WsMU78lHnqkhO8zUeQ732IAG1/Iea36JwIDAQABAoIBAFWyTzjIVjm6Z3dy
YlN8pi5QzzXi1yUbagr0VB449Iow8/hDQ5mO00Aj7P46GGFkgB6IzkiH5oyHmW/G
YtXPT2Aie4VObrfKtzKbe7dDDRKSy7np37hrKri8Rsv9WLwuTQf6XPNsUaEoO58h
r0lImsVacGESUHIupwUmFI0vLrlKoL231REcHTLsyo6dOZHvdOolwelh+pSz0k1k
FYDpM04XdBPayaQ38AL6XoObPTJazv9v8vpl8D2+YBoEPcH+HMy1grnx19AR9Rx2
2WDh45/7o5zrCrAmJM6CeQrdJ1nCChyZL3gpN9ZEAojOofB3x+abwbneRxtUffMq
3uQxXAECgYEA79VmnzU7RhnlrDSSba+9C/4C2cjr+A9uAfNiygC3+25w1ZjUwfVh
u9pdgawltJgeRzOG6lOfxACFKj8qIBL+rlfDIuWBZWUFUfoYJAXmJ9kBdH0vpl12
oVHRXBBZT1GE1AMJzOYX8r5JHB/47ElGxMotfCgV0JwotMidNuAaGbECgYEA6ne4
INw0UTxMXPnWoyGj+g1i3uzfeYNboKTx3C8SX01z23NrCS/sdZDh6yRw7qA0gt6D
OJ85qleqJ49Pa7Xf5CZpKnY7hUbPE5k8coPhh0tbFuqrOIBintMMOQYuBgya2/M4
pGykrMpnN4XyAl+ts9nMhpD5qc4AVInH1bHD71cCgYEAxu5jaLtmpwbkEqqoqoKS
dFgFVU/rKp7hyIxw7M0bzloVDZbvItK+dmryFJUN0XY75yM+TS9/3bvwuNIbxu76
gPIa0d88LTZV62FelMKv3W2KX21XEM+Fjtmmpo6JBdnAK3s5rdNNGfPsAIAkoRlG
sgRhJhK5xYdB3HJqtRG9lIECgYBmwcUukZNULusArHYG1I163zb/oCxoossbYm6l
IvQYVGd8O98jDZ/B/pckaLodupSI7l/wBshNAVKPN92ExRa0dKkOdPas+FV0r2mw
fl/u3XW0W3BiuNF/7dqjezPcbtXHo5alaP/awnHuAYQIyknkUoWyTAM/CgtXAXNV
Ei1ezQKBgC6k/v4L4qvKpa5f9MVNKGyh4iTwRWEz5PS0lRxnMU4e+pEOnXTpRcs2
Ey2A0ncm1KFUT2ZU9ex05funeFjLcK4ATdK64lONHSi16KWXjtesIGZfUzl7swLn
8SDHntGtY1tVb+U3YEA15ZlVrbTygJAaavJ7Occru/ILfroWjbMJ
-----END RSA PRIVATE KEY-----
`;

const rsaPublicKeyPEM = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA26k4gGVllm8w4S4TSGZ2
+naF/pQnzyofyI3tmj5YdkhkYKxVg958dxnDd0KMnFL/tcGmdiEm+RfE9b7TGxhn
ANHRnrKp3+TqgaD8BcE+sdIqa4zpmEybbu27hF3stg7UpgqfYIiKjEYirU9IhTSW
FlHrcwz9zV4hMxMpNEM+Phkupm//6tbnRFphkNntucJ+c3li/pCHlnTMlGO8qiuj
YK/Y5AcOvYLw96/mi/XN+CnKp1Xvd76fuReWndFA35OWICicpurpaKS1f+fe3a10
2Q9dMYiakrkZlRQgRn2VW1WNqluOAzRK8WsMU78lHnqkhO8zUeQ732IAG1/Iea36
JwIDAQAB
-----END PUBLIC KEY-----
`;

const dataToEncrypt = "secret message for RSA";

// -----END GENERATED FIXTURES-----

// --- Helper Functions ---
function arrayBuffersAreEqual(buf1, buf2) {
    if (!buf1 || !buf2 || buf1.byteLength !== buf2.byteLength) return false;
    const view1 = new Uint8Array(buf1);
    const view2 = new Uint8Array(buf2);
    for (let i = 0; i < view1.length; i++) {
        if (view1[i] !== view2[i]) return false;
    }
    return true;
}

function runCryptoTests() {
    console.log("--- [JS] Running Crypto Tests ---");
    const textEncoder = new TextEncoder();
    const textDecoder = new TextDecoder();
    const plaintext = textEncoder.encode("This is a secret message!");
    const dataToSign = textEncoder.encode("Data to be signed");

    try {
        // 1. Hashing
        console.log("\n[1] Hashing (SHA-256)");
        const hash = crypto.hash('sha256', plaintext, 'hex');
        console.log("  - Plaintext:", textDecoder.decode(plaintext));
        console.log("  - Digest (hex):", hash);
        if (hash === '0cf35fb5c5dc8aef50d27f38f7d2e01e050b27e232dc472d86cc1f6c169db11b') {
            console.log("  - Result: OK");
        } else {
            throw new Error("Hash digest does not match expected value.");
        }

        // 2. HMAC
        console.log("\n[2] HMAC (SHA-256)");
        const hmacKey = textEncoder.encode("my-super-secret-hmac-key");
        const hmac = crypto.hmac('sha256', hmacKey, plaintext, 'hex');
        console.log("  - HMAC (hex):", hmac);
        if (hmac === 'f77601f3c9a3f8c36812036457fa0ffed741221548fd7c06c1c71738af002f44') {
            console.log("  - Result: OK");
        } else {
            throw new Error("HMAC does not match expected value.");
        }

        // 3. Symmetric Encryption (AES-256-GCM)
        console.log("\n[3] Symmetric Encryption (AES-256-GCM)");
        const aesKey = crypto.hash('sha256', textEncoder.encode('password123'));
        const iv = textEncoder.encode("12-byte-iv--");
        const { ciphertext, authTag } = crypto.encrypt('aes-256-gcm', aesKey, iv, plaintext);
        const decrypted = crypto.decrypt('aes-256-gcm', aesKey, iv, authTag, ciphertext);
        if (arrayBuffersAreEqual(plaintext, decrypted)) {
            console.log("  - Decryption successful. Result: OK");
        } else {
            throw new Error("Symmetric decryption failed.");
        }

        // 4. Asymmetric Signature (ECDSA)
        console.log("\n[4] Asymmetric Signature (ECDSA with SHA-256)");
        const ecdsaSignature = crypto.ecdsaSign(ecdsaPrivateKeyPEM, 'sha256', dataToSign);
        console.log("  - Signature generated (length):", ecdsaSignature.byteLength);
        const isEcdsaValid = crypto.ecdsaVerify(ecdsaPublicKeyPEM, 'sha256', dataToSign, ecdsaSignature);
        console.log("  - Verification with public key was successful:", isEcdsaValid);
        if (!isEcdsaValid) { throw new Error("ECDSA verification failed"); }
        console.log("  - Result: OK");

        // 5. Asymmetric Signature (RSA-PSS)
        console.log("\n[5] Asymmetric Signature (RSA-PSS with SHA-256)");
        const rsaSignature = crypto.rsaSign(rsaPrivateKeyPEM, 'sha256', dataToSign);
        console.log("  - Signature generated (length):", rsaSignature.byteLength);
        const isRsaValid = crypto.rsaVerify(rsaPublicKeyPEM, 'sha256', dataToSign, rsaSignature);
        console.log("  - Verification with public key was successful:", isRsaValid);
        if (!isRsaValid) { throw new Error("RSA-PSS verification failed"); }
        console.log("  - Result: OK");

        // 6. Asymmetric Encryption (RSA-OAEP)
        console.log("\n[6] Asymmetric Encryption (RSA-OAEP with SHA-256)");
        const plaintextForRsa = textEncoder.encode(dataToEncrypt);
        const rsaCiphertext = crypto.rsaEncrypt(rsaPublicKeyPEM, 'sha256', plaintextForRsa);
        console.log("  - Ciphertext generated (length):", rsaCiphertext.byteLength);
        const decryptedRsa = crypto.rsaDecrypt(rsaPrivateKeyPEM, 'sha256', rsaCiphertext);
        if (arrayBuffersAreEqual(plaintextForRsa, decryptedRsa)) {
             console.log("  - Decryption successful. Result: OK");
        } else {
            throw new Error("Asymmetric decryption failed.");
        }

        // 7. Key Exchange (ECDH)
        console.log("\n[7] Key Exchange (ECDH on P-256)");
        const sharedSecret = crypto.ecdh(ecdsaPrivateKeyPEM, ecdsaPublicKeyPEM);
        console.log("  - Computed Shared Secret (length):", sharedSecret.byteLength);
        if (sharedSecret.byteLength > 0) {
           console.log("  - Result: OK");
        } else {
           throw new Error("ECDH failed to produce a shared secret.");
        }

    } catch (e) {
        console.log("\n!! A cryptographic test failed with an exception:", e);
    }

    console.log("\n--- [JS] Crypto Tests Finished ---");
}

/**
 * handlePacket is called for every MQTT packet that passes through the proxy.
 */
function handlePacket(packet) {
  if (packet.modifiable && packet.type === 'PUBLISH' && packet.topic === 'test/crypto') {
    runCryptoTests();
  }
  return packet;
}

// Export the functions that the proxy will call.
module.exports = {
  handlePacket,
};