package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"log"
)

func main() {
	log.SetFlags(0)

	// --- ECDSA Key Generation (P-256) ---
	ecdsaPrivKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		log.Fatalf("Failed to generate ECDSA private key: %v", err)
	}
	ecdsaPrivKeyBytes, err := x509.MarshalECPrivateKey(ecdsaPrivKey)
	if err != nil {
		log.Fatalf("Failed to marshal ECDSA private key: %v", err)
	}
	ecdsaPrivKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: ecdsaPrivKeyBytes})

	ecdsaPubKeyBytes, err := x509.MarshalPKIXPublicKey(&ecdsaPrivKey.PublicKey)
	if err != nil {
		log.Fatalf("Failed to marshal ECDSA public key: %v", err)
	}
	ecdsaPubKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: ecdsaPubKeyBytes})

	// --- RSA Key Generation (2048-bit) ---
	rsaPrivKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		log.Fatalf("Failed to generate RSA private key: %v", err)
	}
	rsaPrivKeyBytesPKCS1 := x509.MarshalPKCS1PrivateKey(rsaPrivKey)
	rsaPrivKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: rsaPrivKeyBytesPKCS1})

	rsaPubKeyBytes, err := x509.MarshalPKIXPublicKey(&rsaPrivKey.PublicKey)
	if err != nil {
		log.Fatalf("Failed to marshal RSA public key: %v", err)
	}
	rsaPubKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: rsaPubKeyBytes})

	// --- Data for Operations ---
	dataToEncrypt := []byte("secret message for RSA")

	// --- Print Fixtures ---
	fmt.Println("// -----BEGIN GENERATED FIXTURES-----")
	fmt.Println("// Generated by `go run ./cmd/gen_crypto_fixtures`")
	fmt.Printf("\nconst ecdsaPrivateKeyPEM = `%s`;\n", string(ecdsaPrivKeyPEM))
	fmt.Printf("\nconst ecdsaPublicKeyPEM = `%s`;\n", string(ecdsaPubKeyPEM))
	fmt.Printf("\nconst rsaPrivateKeyPEM = `%s`;\n", string(rsaPrivKeyPEM))
	fmt.Printf("\nconst rsaPublicKeyPEM = `%s`;\n", string(rsaPubKeyPEM))
	fmt.Printf("\nconst dataToEncrypt = \"%s\";\n", string(dataToEncrypt))
	fmt.Println("\n// -----END GENERATED FIXTURES-----")
}