version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cmd/zancudo"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/cmd/gen_certs"
    schedule:
      interval: "weekly"
